version: '3.8'

services:
  web:
    image: sirin-board-project
    container_name: board-container
    env_file: .env
    ports:
      - "9100:9100"
    restart: always
    networks:
      - back-tier

networks:
  back-tier:
    external: true